controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
home_show:
    path: /show
    controller: App\Controller\HomeController::show
    methods: ['GET']
